services:
  - type: web
    name: poker-trivia-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn poker_api.main:app --host 0.0.0.0 --port 8000
    autoDeploy: true

  - type: web
    name: poker-trivia-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    autoDeploy: true
