name: CI + Conditional Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint (ruff)
      run: |
        pip install ruff
        ruff check .

    - name: Run Tests
      run: |
        pip install pytest httpx==0.27.0 pytest-asyncio
        export PYTHONPATH=$(pwd)
        pytest

    - name: Trigger Render Deploy 
      if: github.ref == 'refs/heads/main' && success()
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
